repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: local
    hooks:
    # Local Black
    -   id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]
    # Local Flake8 
    -   id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        types: [python]
# To use black from remote 
# -   repo: https://github.com/psf/black
#     rev: 19.3b0
#     hooks:
#     -   id: black
